-- ============================================================
-- BuyWise Israel: Seed all 131 Anglo-market agencies
-- Inserts agency records + Yad2/Madlan source URLs
-- Uses ON CONFLICT DO NOTHING so safe to re-run
-- ============================================================

-- Helper: generate slug from name
-- (lower, strip non-alphanum/space, replace spaces with hyphens)

INSERT INTO public.agencies (name, slug, website, email, phone, cities_covered, is_verified, status, verification_status)
VALUES
  ('Anglo Estates', 'anglo-estates', 'https://angloestates.com', 'info@angloestates.com', '+972-505953249', ARRAY['Beit Shemesh'], false, 'pending', 'pending'),
  ('HaGefen Realty', 'hagefen-realty', 'https://hagefen.com', 'gavrielweinberg@gmail.com', '+972 54-639-3924', ARRAY['Beit Shemesh'], false, 'pending', 'pending'),
  ('Josh Epstein Realty', 'josh-epstein-realty', 'https://beitshemeshrealestate.com', 'realestatebeitshemesh@gmail.com', '+972-2-652-9022', ARRAY['Beit Shemesh'], false, 'pending', 'pending'),
  ('Lemkin Realty', 'lemkin-realty', 'https://aliyahrealty.com', 'barbara.lemkin@gmail.com', '+972 52-286-4129', ARRAY['Beit Shemesh'], false, 'pending', 'pending'),
  ('Yigal Realty', 'yigal-realty', 'https://www.yigal-realty.com', 'naomi@yigal-realty.com', '052-892-6607', ARRAY['Beit Shemesh'], false, 'pending', 'pending'),
  ('Ilana Fish Realty', 'ilana-fish-realty', 'https://ilanarealty.com', 'ilanafishrealty@gmail.com', '+972-2-9922320', ARRAY['Beit Shemesh'], false, 'pending', 'pending'),
  ('Mordy Real Estate', 'mordy-real-estate', 'https://www.mordyrealestatebeitshemesh.com', 'sales@mordyrealestatebeitshemesh.com', '+972-58-791-5065', ARRAY['Beit Shemesh'], false, 'pending', 'pending'),
  ('Gordon Realty', 'gordon-realty', 'https://gordonrealtyrbs.com', 'r0585148478@gmail.com', '+972585148478', ARRAY['Beit Shemesh'], false, 'pending', 'pending'),
  ('Israel Home Advisors', 'israel-home-advisors', 'https://israelhomebuyers.com', NULL, NULL, ARRAY['Beit Shemesh'], false, 'pending', 'pending'),
  ('Anglo-Saxon Efrat', 'anglo-saxon-efrat', 'https://www.anglo-saxon.co.il/en/branches/single/?id=3', 'efrat-gushetzion@anglo-saxon.co.il', '02-993-1606', ARRAY['Efrat'], false, 'pending', 'pending'),
  ('Efrat Real Estate', 'efrat-real-estate', 'https://efratrealty.co.il/en/home-2/', 'oshrip.nadlan@gmail.com', '053-555-5107', ARRAY['Efrat'], false, 'pending', 'pending'),
  ('Gabai Real Estate', 'gabai-real-estate', 'https://gabairealestate.com', 'office@gabairealestate.com', '+972 52-614-1442', ARRAY['Efrat'], false, 'pending', 'pending'),
  ('Noam Homes', 'noam-homes', 'https://www.noamhomes.com', 'office@noamhomes.com', '+972-52-870-2387', ARRAY['Efrat', 'Gush Etzion'], false, 'pending', 'pending'),
  ('Angel Realty', 'angel-realty', 'https://angelrealty.co.il/index.php?language=English', 'realsnir@gmail.com', '052-458-8716', ARRAY['Gush Etzion'], false, 'pending', 'pending'),
  ('Anglo-Saxon Jerusalem', 'anglo-saxon-jerusalem', 'https://www.anglo-saxon.co.il/en/branches/single/?id=1', 'jerusalem@anglo-saxon.co.il', '073-7597880', ARRAY['Jerusalem'], false, 'pending', 'pending'),
  ('Century 21 Jerusalem', 'century-21-jerusalem', 'https://www.century21jerusalem.com', 'office@century21jerusalem.com', '+972-2-5672030', ARRAY['Jerusalem'], false, 'pending', 'pending'),
  ('Prosperity Real Estate', 'prosperity-real-estate', 'https://prosperity-realestate.com', 'info@prosperity-realestate.com', '+972 2-5670303', ARRAY['Jerusalem'], false, 'pending', 'pending'),
  ('RE/MAX Jerusalem', 'remax-jerusalem', 'https://remaxjerusalem.com', 'vision@remax.co.il', '+9722-673-1661', ARRAY['Jerusalem'], false, 'pending', 'pending'),
  ('Oren Cohen Group', 'oren-cohen-group', 'https://www.orencohengroup.com', 'marketing@orencohengroup.com', '+972-2-6634070', ARRAY['Jerusalem'], false, 'pending', 'pending'),
  ('CapitIL Real Estate', 'capitil-real-estate', 'https://capitil.com', NULL, NULL, ARRAY['Jerusalem'], false, 'pending', 'pending'),
  ('JHomes Jerusalem Real Estate', 'jhomes-jerusalem-real-estate', 'https://www.jhomes.co.il', 'yoav@jhomes.co.il', '+972-2-381-9531', ARRAY['Jerusalem'], false, 'pending', 'pending'),
  ('Anglo-Saxon Modiin', 'anglo-saxon-modiin', 'https://www.anglo-saxon.co.il/en/branches/single/?id=31', 'ofer-a@anglo-saxon.co.il', '073-7026277', ARRAY['Modi''in'], false, 'pending', 'pending'),
  ('French Connection', 'french-connection', 'https://french-connection.co.il/en/home/', NULL, NULL, ARRAY['Modi''in'], false, 'pending', 'pending'),
  ('HaBayit Shelanu', 'habayit-shelanu', 'https://modiinrealestate.com/', 'inquiries@modiinrealestate.com', '+972 58-771-1523', ARRAY['Modi''in'], false, 'pending', 'pending'),
  ('Lev Nadlan', 'lev-nadlan', 'https://www.levnadlan.co.il/', 'Lev.hanadlan1@gmail.com', '050-8829454', ARRAY['Modi''in'], false, 'pending', 'pending'),
  ('Anglo-Saxon Netanya', 'anglo-saxon-netanya', 'https://www.anglo-saxon.co.il/en/branches/single/?id=153', 'natanya@anglo-saxon.co.il', '073-7028610', ARRAY['Netanya'], false, 'pending', 'pending'),
  ('Diamond Realty Israel', 'diamond-realty-israel', 'https://www.diamondrealtyisrael.com/en/', 'contact@diamondrealtyisrael.com', '052-406-6007', ARRAY['Netanya'], false, 'pending', 'pending'),
  ('Home in Israel', 'home-in-israel', 'https://homeinisrael.com/en/', 'info@homeinisrael.net', '+972-98866270', ARRAY['Netanya'], false, 'pending', 'pending'),
  ('Maxine Marks Luxury Property', 'maxine-marks-luxury-property', 'https://www.luxury-propertyinisrael.com', NULL, NULL, ARRAY['Netanya'], false, 'pending', 'pending'),
  ('Liora Ben Ari', 'liora-ben-ari', 'https://liorabenari.com', 'hello@liorabenari.com', '+972-54-662-3322', ARRAY['Netanya'], false, 'pending', 'pending'),
  ('Anglo-Saxon Ra''anana', 'anglo-saxon-raanana', 'https://www.anglo-saxon.co.il/en/branches/single/?id=24', 'raanana@anglo-saxon.co.il', '073-7536451', ARRAY['Ra''anana'], false, 'pending', 'pending'),
  ('Call Dena', 'call-dena', 'https://calldenahomes.com', 'calldenahomes@gmail.com', '+972-55-504-3605', ARRAY['Ra''anana'], false, 'pending', 'pending'),
  ('Keller Williams Traklin Nadlan', 'keller-williams-traklin-nadlan', 'http://www.traklin-art.co.il', 'roy@traklin-art.co.il', '+972 9-748-6611', ARRAY['Ra''anana'], false, 'pending', 'pending'),
  ('RE/MAX ONE Ra''anana', 'remax-one-raanana', 'https://www.remax-israel.com/en/offices/center/raanana/remax-one-raanana/83006', 'one.raanana@remax.co.il', '+972 1-800-351-351', ARRAY['Ra''anana'], false, 'pending', 'pending'),
  ('Realty Executives Ra''anana', 'realty-executives-raanana', 'https://www.rexe.co.il', NULL, NULL, ARRAY['Ra''anana'], false, 'pending', 'pending'),
  ('NYG Nefussy Group', 'nyg-nefussy-group', 'https://nyg.co.il/en/', 'info@nyg.co.il', '+97253-3524653', ARRAY['Ra''anana'], false, 'pending', 'pending'),
  ('Rimon Nadlan', 'rimon-nadlan', 'https://www.rimonnadlan.com/en/', 'contact@rimonnadlan.com', '+972-54-4379986', ARRAY['Ra''anana'], false, 'pending', 'pending'),
  ('Yael Ankaoua Real Estate', 'yael-ankaoua-real-estate', NULL, 'yaelankaoua@gmail.com', '+972 52-574-1279', ARRAY['Ra''anana'], false, 'pending', 'pending'),
  ('Anglo-Saxon Tel Aviv', 'anglo-saxon-tel-aviv', 'https://www.astlv.co.il', 'office@astlv.com', '072-3922214', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('EXP Israel', 'exp-israel', 'https://www.expisrael.co.il', 'info@expisrael.co.il', '+972 52 528 4499', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Israel Sotheby''s International Realty', 'israel-sothebys-international-realty', 'https://www.israelsir.com', 'office@israelsir.com', '+972 3-771-0977', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('ProperTLV', 'propertlv', 'https://propertlv.com', 'tova@propertlv.com', '+972 54 627 0099', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Erez Properties', 'erez-properties', 'https://www.erezrealestate.co.il', NULL, NULL, ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('TLV Realty', 'tlv-realty', 'https://tlv-realty.co.il', 'eyal@tlv-realty.co.il', '054-595-4225', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Zemour Exclusive Realty', 'zemour-exclusive-realty', 'https://www.zemour-realty.com', 'office@zemour-realty.com', '+972.3.744.4844', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Ronkin Real Estate', 'ronkin-real-estate', 'https://ronkin-list.com', 'info@ronkin-list.com', '+972-55-507-2892', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Montefiore Real Estate Group', 'montefiore-real-estate-group', 'https://www.mfreg.com', 'contact@mfreg.com', '+972-50-3573809', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('BARNES Israel', 'barnes-israel', 'https://www.barnes-israel.com', 'israel@barnes-international.com', '+972 54 36 00 082', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('GRE Goldstein Real Estate', 'gre-goldstein-real-estate', 'https://gre-israel.com', 'Daniel@gre-israel.com', '+972 545976272', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Anglo-Saxon Givat Shmuel', 'anglo-saxon-givat-shmuel', 'https://www.anglo-saxon.co.il/en/branches/single/?id=50', 'pettikva@anglo-saxon.co.il', '073-7023299', ARRAY['Givat Shmuel'], false, 'pending', 'pending'),
  ('Keter Advisors', 'keter-advisors', 'https://keteradvisors.com/city/givat-shmuel/', 'info@keteradvisors.com', '972-52-682-9367', ARRAY['Givat Shmuel'], false, 'pending', 'pending'),
  ('Semerenko Group', 'semerenko-group', 'https://semerenkogroup.com', 'hello@semerenkogroup.com', '0583925901', ARRAY['Givat Shmuel', 'Petah Tikva', 'Caesarea', 'Ramat Gan', 'Zichron Yaakov'], false, 'pending', 'pending'),
  ('12 Real Estate', '12-real-estate', 'https://michael12realestate.com', 'Michael.f@12-realty.com', '+972 53 717 0525', ARRAY['Haifa'], false, 'pending', 'pending'),
  ('Anglo-Saxon Haifa', 'anglo-saxon-haifa', 'https://www.anglo-saxon.co.il/en/branches/single/?id=44', 'mhacarmel@anglo-saxon.co.il', '073-7028320', ARRAY['Haifa'], false, 'pending', 'pending'),
  ('RE/MAX Selected Haifa', 'remax-selected-haifa', 'https://remaxhaifa.co.il', 'danigeorgteam@gmail.com', '+972 74-7033777', ARRAY['Haifa'], false, 'pending', 'pending'),
  ('Anglo-Saxon Herzliya Pituach', 'anglo-saxon-herzliya-pituach', 'https://real-estate-herzliya-pituach.com', 'info@ashp.co.il', '052-3533247', ARRAY['Herzliya'], false, 'pending', 'pending'),
  ('ID Real Estate Israel', 'id-real-estate-israel', 'https://www.idrealestateisrael.com', 'idrealestate.il@gmail.com', '+972 58-620-2220', ARRAY['Herzliya'], false, 'pending', 'pending'),
  ('Iltam Real Estate', 'iltam-real-estate', 'https://iltam.co.il', 'info@iltam.co.il', '+972-9-374-1307', ARRAY['Herzliya'], false, 'pending', 'pending'),
  ('Square34', 'square34', 'https://square34.com', NULL, NULL, ARRAY['Herzliya'], false, 'pending', 'pending'),
  ('Uri Tal Real Estate', 'uri-tal-real-estate', 'https://www.herzliya-pituach.com', 'Uri@urital.com', '+972-72-3201217', ARRAY['Herzliya'], false, 'pending', 'pending'),
  ('Israel Habitat', 'israel-habitat', 'https://israel-habitat.com', 'info@israelhabitat.com', '+972 77 455 0102', ARRAY['Herzliya'], false, 'pending', 'pending'),
  ('Barnea Luxury Real Estate', 'barnea-luxury-real-estate', 'https://barnealuxuryrealestate.com', NULL, '+972 50-951-5067', ARRAY['Herzliya'], false, 'pending', 'pending'),
  ('VeraPrime', 'veraprime', 'https://www.veraprime.co.il', NULL, NULL, ARRAY['Herzliya'], false, 'pending', 'pending'),
  ('RE/MAX ONE Kfar Saba', 'remax-one-kfar-saba', 'https://www.remax-israel.com/ONE', 'one@remax.co.il', '1-800-351-351', ARRAY['Kfar Saba'], false, 'pending', 'pending'),
  ('RE/MAX Atid Ma''ale Adumim', 'remax-atid-maale-adumim', 'https://www.remax-israel.com/atid', 'ma@remaxjerusalem.com', '072-3926631', ARRAY['Ma''ale Adumim'], false, 'pending', 'pending'),
  ('Anglo-Saxon Mevaseret', 'anglo-saxon-mevaseret', 'https://www.anglo-saxon.co.il/en/branches/single/?id=2', 'mevvaseret@anglo-saxon.co.il', '073-7531529', ARRAY['Mevaseret Zion'], false, 'pending', 'pending'),
  ('Racer Real Estate', 'racer-real-estate', 'https://www.racerrealestate.com', 'racer-ltd@outlook.com', '054-4592-444', ARRAY['Mevaseret Zion'], false, 'pending', 'pending'),
  ('S+ Real Estate', 'splus-real-estate', 'https://splusrealestate.co.il/en/about-us/', 'office@splusrealestate.co.il', '054-928-3437', ARRAY['Mevaseret Zion'], false, 'pending', 'pending'),
  ('Anglo-Saxon Petah Tikva', 'anglo-saxon-petah-tikva', 'https://www.anglo-saxon.co.il/en/branches/single/?id=50', 'pettikva@anglo-saxon.co.il', '073-7023299', ARRAY['Petah Tikva'], false, 'pending', 'pending'),
  ('RE/MAX Infinity Petah Tikva', 'remax-infinity-petah-tikva', 'https://remaxpt.co.il', 'remaxptt@gmail.com', '072-395-4553', ARRAY['Petah Tikva'], false, 'pending', 'pending'),
  ('Alex Losky Real Estate Group', 'alex-losky-real-estate-group', 'https://losky.co.il/', 'contact@losky.co.il', '+972-2-623.55.95', ARRAY['Ashdod'], false, 'pending', 'pending'),
  ('Anglo-Saxon Ashdod', 'anglo-saxon-ashdod', 'https://www.anglo-saxon.co.il/en/branches/single/?id=152', 'ashdod@anglo-saxon.co.il', '073-7536044', ARRAY['Ashdod'], false, 'pending', 'pending'),
  ('Immoyard', 'immoyard', 'https://www.immoyard.com', 'immoyard1@gmail.com', '+972 54-6323252', ARRAY['Ashdod'], false, 'pending', 'pending'),
  ('Anglo-Saxon Ashkelon', 'anglo-saxon-ashkelon', 'https://www.anglo-saxon.co.il/en/branches/single/?id=35', 'ashkelon@anglo-saxon.co.il', '073-7534672', ARRAY['Ashkelon'], false, 'pending', 'pending'),
  ('Ashkelon Rentals', 'ashkelon-rentals', 'https://ashkelonrentals.com', 'davidz@ashkelonproperties.com', '+972 58-783-7436', ARRAY['Ashkelon'], false, 'pending', 'pending'),
  ('Mr Ashkelon', 'mr-ashkelon', 'https://mrashkelon.com', 'motti@mrashkelon.com', '054-731-2118', ARRAY['Ashkelon'], false, 'pending', 'pending'),
  ('Stephen Epstein Real Estate', 'stephen-epstein-real-estate', 'https://stephen-epstein.com', NULL, NULL, ARRAY['Ashkelon'], false, 'pending', 'pending'),
  ('Ashkelon Properties', 'ashkelon-properties', 'https://www.ashkelonproperties.com', 'davidz@AshkelonProperties.com', '+972 54-433-2621', ARRAY['Ashkelon'], false, 'pending', 'pending'),
  ('Anglo Saxon Beer Sheva', 'anglo-saxon-beer-sheva', 'https://www.anglo-saxon.co.il/en/branches/single/?id=65', 'Bsheva@anglo-saxon.co.il', '073-7027103', ARRAY['Beer Sheva'], false, 'pending', 'pending'),
  ('Davidson Real Estate', 'davidson-real-estate', 'https://davidson-realestate.com', 'info@davidson-realestate.com', '+972 52-484-3326', ARRAY['Caesarea'], false, 'pending', 'pending'),
  ('Israel Property Hub', 'israel-property-hub', 'https://israelpropertyhub.com', 'info@israelpropertyhub.com', '+972-54-8886006', ARRAY['Caesarea'], false, 'pending', 'pending'),
  ('Prime Luxury Real Estate', 'prime-luxury-real-estate', 'https://primeluxuaryhomes.com', 'info@primeluxuaryhomes.com', '+972 54-477-2275', ARRAY['Caesarea'], false, 'pending', 'pending'),
  ('Rita Real Estate', 'rita-real-estate', NULL, NULL, NULL, ARRAY['Caesarea'], false, 'pending', 'pending'),
  ('Korenfld Real Estate', 'korenfld-real-estate', 'https://www.korenfld.com/en/', 'office@korenfld.com', '+972-8-6344514', ARRAY['Eilat'], false, 'pending', 'pending'),
  ('RE/MAX Sea Side Eilat', 'remax-sea-side-eilat', 'https://www.remax-israel.com/en/offices/jerusalem-and-the-south/eilat/', 'eladeibi24@gmail.com', '+972 52-635-5504', ARRAY['Eilat'], false, 'pending', 'pending'),
  ('Unlimitd Real Estate', 'unlimitd-real-estate', 'https://www.unlimitedeilat.com/', 'nh1027@gmail.com', '052-8950245', ARRAY['Eilat'], false, 'pending', 'pending'),
  ('Anglo-Saxon Hadera', 'anglo-saxon-hadera', 'https://www.anglo-saxon.co.il/en/branches/single/?id=43', 'hadera@anglo-saxon.co.il', '073-7533784', ARRAY['Hadera'], false, 'pending', 'pending'),
  ('Anglo-Saxon Hod HaSharon', 'anglo-saxon-hod-hasharon', 'https://www.anglo-saxon.co.il/en/branches/single/?id=12', 'hhasharo@anglo-saxon.co.il', '073-7026195', ARRAY['Hod HaSharon'], false, 'pending', 'pending'),
  ('Yokra Estate', 'yokra-estate', 'https://www.yokra-estate.co.il/en/properties/hod-hasharon.html', 'yokra.estate@gmail.com', '054-5455955', ARRAY['Hod HaSharon'], false, 'pending', 'pending'),
  ('Anglo-Saxon Pardes Hanna', 'anglo-saxon-pardes-hanna', 'https://www.anglo-saxon.co.il/en/branches/single/?id=49', 'pardeshana@anglo-saxon.co.il', '073-7534575', ARRAY['Pardes Hanna'], false, 'pending', 'pending'),
  ('Pardes Hanna Real Estate', 'pardes-hanna-real-estate', 'https://pardeschanarealestate.com/', 'pardeshanarealestate@gmail.com', '+972 54-723-3455', ARRAY['Pardes Hanna'], false, 'pending', 'pending'),
  ('TaylorMade Real Estate', 'taylormade-real-estate', 'https://rsnadlan.co.il', 'netta.taylor@gmail.com', '+972 54-764-9017', ARRAY['Pardes Hanna'], false, 'pending', 'pending'),
  ('Anglo-Saxon Ramat Gan', 'anglo-saxon-ramat-gan', 'https://www.anglo-saxon.co.il/en/branches/single/?id=63', 'ramatgan@anglo-saxon.co.il', '073-7533410', ARRAY['Ramat Gan'], false, 'pending', 'pending'),
  ('Daon Group Real Estate', 'daon-group-real-estate', 'https://daonrealestate.com', 'contact@daonrealestate.com', '+972-54-830-5970', ARRAY['Zichron Yaakov'], false, 'pending', 'pending'),
  ('Gary Fieldman Real Estate', 'gary-fieldman-real-estate', 'https://www.gary-fieldman.com', 'garyfieldman1@gmail.com', '050-33-55-779', ARRAY['Zichron Yaakov'], false, 'pending', 'pending'),
  ('My Israel Property', 'my-israel-property', 'https://www.myisraelproperty.com', 'info@myisraelproperty.com', '+972-52-502-2990', ARRAY['Zichron Yaakov'], false, 'pending', 'pending'),
  ('Sharon Levi Real Estate', 'sharon-levi-real-estate', 'https://www.sharonlevi.com', 'sharony40@gmail.com', '+972 54-306-1968', ARRAY['Zichron Yaakov'], false, 'pending', 'pending'),
  ('Landsman', 'landsman', 'https://www.landsman.co', NULL, NULL, ARRAY['Tel Aviv', 'Jerusalem', 'Netanya'], false, 'pending', 'pending'),
  ('Kim Bash Real Estate', 'kim-bash-real-estate', 'https://kimbashrealestate.com', 'kim@kimbashrealestate.com', '+972 54 441 5704', NULL, false, 'pending', 'pending'),
  ('Evenis Group', 'evenis-group', 'https://www.evenisgroup.com', 'contact@evenisgroup.com', '+(972) 747571578', NULL, false, 'pending', 'pending'),
  ('EC Nadlan', 'ec-nadlan', 'https://ecnadlan.com', 'contact@ecnadlan.com', '+972 03-5270024', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Adar Luxury Realty', 'adar-luxury-realty', 'https://adarluxuryrealty.com', 'lior@adarluxuryrealty.com', '+972 50-543-1146', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('RE/MAX Ocean', 'remax-ocean', 'https://www.remax-israel.com/en/offices/center/tel-aviv-jaffa-central-tel-aviv/remax-ocean-rimkas-ocean/5064', NULL, NULL, ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Aikort Real Estate', 'aikort-real-estate', 'https://aikort.co.il', NULL, '+972 3-5223032', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('TheAgencyTLV', 'theagencytlv', 'https://theagencytlv.com', 'info@theagencytlv.com', '+972 (052) 777 1715', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Daniel Bouzaglo Jerusalem Real Estate', 'daniel-bouzaglo-jerusalem-real-estate', 'https://daniels-assets.com', NULL, NULL, ARRAY['Jerusalem'], false, 'pending', 'pending'),
  ('Ir Hamoriah Realty', 'ir-hamoriah-realty', 'https://irhamoriah.co.il/en', 'IrHamoriah@gmail.com', '+972-25814666', ARRAY['Jerusalem'], false, 'pending', 'pending'),
  ('The Getter Group', 'the-getter-group', 'https://thegettergroup.com', 'contact@thegettergroup.com', '+972 58-318-0000', ARRAY['Jerusalem'], false, 'pending', 'pending'),
  ('Kaufman Realty', 'kaufman-realty', 'https://kaufmanrlty.com', 'yoel@kaufmanrlty.com', '+972-542074969', ARRAY['Jerusalem'], false, 'pending', 'pending'),
  ('RE/MAX Grand Haifa', 'remax-grand-haifa', 'https://www.remax-israel.com/en/offices/north/haifa/remax-grand/5149', 'ic.ethics@gmail.com', '04-8884000', ARRAY['Haifa'], false, 'pending', 'pending'),
  ('Goldman Group', 'goldman-group', 'https://ggisrael.com', NULL, NULL, ARRAY['Ra''anana'], false, 'pending', 'pending'),
  ('Olim Advisors', 'olim-advisors', 'https://www.olimadvisors.com', 'litzhaki@olimadvisors.com', '+972-52-380-6020', NULL, false, 'pending', 'pending'),
  ('Tivuch Shelly', 'tivuch-shelly', 'https://www.tivuchshelly.com', 'office@tivuchshelly.com', '+972 2-566-2499', ARRAY['Netanya'], false, 'pending', 'pending'),
  ('Elite Israel Realty', 'elite-israel-realty', 'https://eliteisraelrealty.com', 'robernst@gmail.com', '+972 58 636 6107', ARRAY['Beit Shemesh'], false, 'pending', 'pending'),
  ('Israel Properties Stamelman', 'israel-properties-stamelman', 'https://www.israel-properties.com', 'info@israel-properties.com', '+972 50 446 9515', ARRAY['Beit Shemesh'], false, 'pending', 'pending'),
  ('Nadlan 360', 'nadlan-360', 'https://nadlan360.co.il/en', 'aviv@nadlan360.co.il', '04-6249991', ARRAY['Zichron Yaakov'], false, 'pending', 'pending'),
  ('iInvest Israel', 'iinvest-israel', 'https://iinvestisrael.com', NULL, NULL, NULL, false, 'pending', 'pending'),
  ('Trusted House', 'trusted-house', 'https://www.trustedhouse.com', 'help@trustedhouse.com', '+972 586459231', NULL, false, 'pending', 'pending'),
  ('Beauchamp Estates', 'beauchamp-estates', 'https://www.beauchampestates.com/tel-aviv', 'israel@beauchampestates.com', '+972 (0)3 555 5111', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Splendor Israel', 'splendor-israel', 'https://splendor-israel.com', 'contact@splendor-israel.com', '+972-54-6501650', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Vered Aminov Real Estate', 'vered-aminov-real-estate', 'https://veredaminov.co.il/en', 'info@veredaminov.co.il', '+972-3-5095389', ARRAY['Tel Aviv'], false, 'pending', 'pending'),
  ('Engel Nehassim', 'engel-nehassim', 'https://engel-telaviv.com', 'engelp26@gmail.com', '052 365 07 88', ARRAY['Tel Aviv'], false, 'pending', 'pending')
ON CONFLICT (slug) DO NOTHING;


-- ============================================================
-- Insert Yad2 + Madlan source URLs into agency_sources
-- Only for agencies that have them in the CSV
-- ============================================================

INSERT INTO public.agency_sources (agency_id, source_type, source_url, is_active, priority)
SELECT a.id, 'yad2', s.url, true, 2
FROM (VALUES
  ('lemkin-realty',                   'https://www.yad2.co.il/realestate/agency/3483016/forsale'),
  ('mordy-real-estate',               'https://www.yad2.co.il/realestate/agency/7927426/forsale'),
  ('gordon-realty',                   'https://www.yad2.co.il/realestate/agency/8019859/forsale'),
  ('efrat-real-estate',               'https://www.yad2.co.il/realestate/agency/8832122/forsale'),
  ('gabai-real-estate',               'https://www.yad2.co.il/realestate/agency/6719929/forsale'),
  ('noam-homes',                      'https://www.yad2.co.il/realestate/agency/6234939/forsale'),
  ('angel-realty',                    'https://www.yad2.co.il/realestate/agency/1964637/forsale'),
  ('anglo-saxon-jerusalem',           'https://www.yad2.co.il/realestate/agency/352115/forsale'),
  ('century-21-jerusalem',            'https://www.yad2.co.il/realestate/agency/303556/forsale'),
  ('remax-jerusalem',                 'https://www.yad2.co.il/realestate/agency/6774487/forsale'),
  ('oren-cohen-group',                'https://www.yad2.co.il/realestate/agency/8965244/forsale'),
  ('capitil-real-estate',             'https://www.yad2.co.il/realestate/agency/5972160/forsale'),
  ('jhomes-jerusalem-real-estate',    'https://www.yad2.co.il/realestate/agency/9073501/forsale'),
  ('anglo-saxon-modiin',              'https://www.yad2.co.il/realestate/agency/1856812/forsale'),
  ('french-connection',               'https://www.yad2.co.il/realestate/agency/3757000/forsale'),
  ('lev-nadlan',                      'https://www.yad2.co.il/realestate/agency/6597661/forsale'),
  ('anglo-saxon-netanya',             'https://www.yad2.co.il/realestate/agency/8565575/forsale'),
  ('home-in-israel',                  'https://www.yad2.co.il/realestate/agency/3234998/forsale'),
  ('maxine-marks-luxury-property',    'https://www.yad2.co.il/realestate/agency/3736085/forsale'),
  ('anglo-saxon-raanana',             'https://www.yad2.co.il/realestate/agency/910503/forsale'),
  ('keller-williams-traklin-nadlan',  'https://www.yad2.co.il/realestate/agency/6271846/forsale'),
  ('remax-one-raanana',               'https://www.yad2.co.il/realestate/agency/1362875/forsale'),
  ('realty-executives-raanana',       'https://www.yad2.co.il/realestate/agency/3845617/forsale'),
  ('nyg-nefussy-group',               'https://www.yad2.co.il/realestate/agency/7410556/forsale'),
  ('rimon-nadlan',                    'https://www.yad2.co.il/realestate/agency/8669092/forsale'),
  ('anglo-saxon-tel-aviv',            'https://www.yad2.co.il/realestate/agency/57258/forsale'),
  ('israel-sothebys-international-realty', 'https://www.yad2.co.il/realestate/agency/364822/forsale'),
  ('propertlv',                       'https://www.yad2.co.il/realestate/agency/9131060/forsale'),
  ('erez-properties',                 'https://www.yad2.co.il/realestate/agency/7965921/forsale'),
  ('tlv-realty',                      'https://www.yad2.co.il/realestate/agency/3188911/forsale'),
  ('zemour-exclusive-realty',         'https://www.yad2.co.il/realestate/agency/5349253/forsale'),
  ('montefiore-real-estate-group',    'https://www.yad2.co.il/realestate/agency/6816246/forsale'),
  ('barnes-israel',                   'https://www.yad2.co.il/realestate/agency/8489965/forsale'),
  ('anglo-saxon-haifa',               'https://www.yad2.co.il/realestate/agency/2495555/forsale'),
  ('remax-selected-haifa',            'https://www.yad2.co.il/realestate/agency/9091011/forsale'),
  ('anglo-saxon-herzliya-pituach',    'https://www.yad2.co.il/realestate/agency/7457257/forsale'),
  ('iltam-real-estate',               'https://www.yad2.co.il/realestate/agency/8840578/forsale'),
  ('israel-habitat',                  'https://www.yad2.co.il/realestate/agency/5308622/forsale'),
  ('barnea-luxury-real-estate',       'https://www.yad2.co.il/realestate/agency/6388876/forsale'),
  ('veraprime',                       'https://www.yad2.co.il/realestate/agency/2472740/forsale'),
  ('remax-one-kfar-saba',             'https://www.yad2.co.il/realestate/agency/1362875/forsale'),
  ('anglo-saxon-mevaseret',           'https://www.yad2.co.il/realestate/agency/694188/forsale'),
  ('racer-real-estate',               'https://www.yad2.co.il/realestate/agency/2300140/forsale'),
  ('splus-real-estate',               'https://www.yad2.co.il/realestate/agency/8864962/forsale'),
  ('remax-infinity-petah-tikva',      'https://www.yad2.co.il/realestate/agency/8872282/forsale'),
  ('anglo-saxon-ashdod',              'https://www.yad2.co.il/realestate/agency/3445182/forsale'),
  ('anglo-saxon-ashkelon',            'https://www.yad2.co.il/realestate/agency/917111/forsale'),
  ('mr-ashkelon',                     'https://www.yad2.co.il/realestate/agency/3310173/forsale'),
  ('anglo-saxon-beer-sheva',          'https://www.yad2.co.il/realestate/agency/2648042/forsale'),
  ('israel-property-hub',             'https://www.yad2.co.il/realestate/agency/602759/forsale'),
  ('rita-real-estate',                'https://www.yad2.co.il/realestate/agency/1053323/forsale'),
  ('remax-sea-side-eilat',            'https://www.yad2.co.il/realestate/agency/4899834/forsale'),
  ('anglo-saxon-hadera',              'https://www.yad2.co.il/realestate/agency/981093/forsale'),
  ('anglo-saxon-hod-hasharon',        'https://www.yad2.co.il/realestate/agency/1342681/forsale'),
  ('yokra-estate',                    'https://www.yad2.co.il/realestate/agency/5675482/forsale'),
  ('anglo-saxon-pardes-hanna',        'https://www.yad2.co.il/realestate/agency/82259/forsale'),
  ('taylormade-real-estate',          'https://www.yad2.co.il/realestate/agency/3841931/forsale'),
  ('anglo-saxon-ramat-gan',           'https://www.yad2.co.il/realestate/agency/2277586/forsale'),
  ('daon-group-real-estate',          'https://www.yad2.co.il/realestate/agency/7161220/forsale'),
  ('my-israel-property',              'https://www.yad2.co.il/realestate/agency/7396177/forsale'),
  ('landsman',                        'https://www.yad2.co.il/realestate/agency/6255400/forsale'),
  ('evenis-group',                    'https://www.yad2.co.il/realestate/agency/8626785/forsale'),
  ('adar-luxury-realty',              'https://www.yad2.co.il/realestate/agency/6061479/forsale'),
  ('remax-ocean',                     'https://www.yad2.co.il/realestate/agency/5691165/forsale'),
  ('unlimitd-real-estate',            'https://www.yad2.co.il/realestate/agency/3457686/forsale')
) AS s(slug, url)
JOIN public.agencies a ON a.slug = s.slug
ON CONFLICT DO NOTHING;


INSERT INTO public.agency_sources (agency_id, source_type, source_url, is_active, priority)
SELECT a.id, 'madlan', s.url, true, 2
FROM (VALUES
  ('anglo-saxon-efrat',               'https://www.madlan.co.il/agentsOffice/re_office_iOCW4xaNcta'),
  ('noam-homes',                      'https://www.madlan.co.il/agentsOffice/re_office_kBVOXDPaEWo'),
  ('anglo-saxon-jerusalem',           'https://www.madlan.co.il/agentsOffice/re_office_gyPv4D1DUIh'),
  ('century-21-jerusalem',            'https://www.madlan.co.il/agentsOffice/re_office_NXgMUyn8dD'),
  ('prosperity-real-estate',          'https://www.madlan.co.il/agentsOffice/re_office_kkv4EqiRNPG'),
  ('remax-jerusalem',                 'https://www.madlan.co.il/agentsOffice/re_office_d2bbUJZ5sE2'),
  ('oren-cohen-group',                'https://www.madlan.co.il/agentsOffice/re_office_osIiJ4Kj3a'),
  ('capitil-real-estate',             'https://www.madlan.co.il/agentsOffice/re_office_dliYXePXYFc'),
  ('jhomes-jerusalem-real-estate',    'https://www.madlan.co.il/agentsOffice/re_office_cEBDGeLZq3S'),
  ('anglo-saxon-modiin',              'https://www.madlan.co.il/agentsOffice/re_office_fr9HVPux4WM'),
  ('french-connection',               'https://www.madlan.co.il/agentsOffice/re_office_hrV0U2FYB0e'),
  ('lev-nadlan',                      'https://www.madlan.co.il/agentsOffice/re_office_iLQYSLi2pXW'),
  ('home-in-israel',                  'https://www.madlan.co.il/agentsOffice/re_office_hYEXMVD4gyL'),
  ('maxine-marks-luxury-property',    'https://www.madlan.co.il/agentsOffice/re_office_jagt9aY2cb8'),
  ('anglo-saxon-raanana',             'https://www.madlan.co.il/agentsOffice/re_office_e62fJefRtNg'),
  ('keller-williams-traklin-nadlan',  'https://www.madlan.co.il/agentsOffice/re_office_cvwpZU5D0tN'),
  ('remax-one-raanana',               'https://www.madlan.co.il/agentsOffice/re_office_kv485hRazN'),
  ('realty-executives-raanana',       'https://www.madlan.co.il/agentsOffice/re_office_jvuEg7IyLXX'),
  ('anglo-saxon-tel-aviv',            'https://www.madlan.co.il/agentsOffice/re_office_gxYCScPXsAK'),
  ('exp-israel',                      'https://www.madlan.co.il/agentsOffice/re_office_WbLNIGG3bzG9S'),
  ('israel-sothebys-international-realty', 'https://www.madlan.co.il/agentsOffice/re_office_imxQvbaxNOg'),
  ('propertlv',                       'https://www.madlan.co.il/agentsOffice/re_office_fw3ntXAXHbw'),
  ('erez-properties',                 'https://www.madlan.co.il/agentsOffice/re_office_ecDcGTy8kiA'),
  ('tlv-realty',                      'https://www.madlan.co.il/agentsOffice/re_office_dtTJE1wxzwd'),
  ('zemour-exclusive-realty',         'https://www.madlan.co.il/agentsOffice/re_office_ckZoazpHIJF'),
  ('montefiore-real-estate-group',    'https://www.madlan.co.il/agentsOffice/re_office_tFfjfn7Orp'),
  ('barnes-israel',                   'https://www.madlan.co.il/agentsOffice/re_office_jY9nIJ65BaP'),
  ('anglo-saxon-givat-shmuel',        'https://www.madlan.co.il/agentsOffice/re_office_ho6VMcBoXyg'),
  ('anglo-saxon-haifa',               'https://www.madlan.co.il/agentsOffice/re_office_dLT8um1ZlOh'),
  ('remax-selected-haifa',            'https://www.madlan.co.il/agentsOffice/re_office_eGPI1sqWpwi'),
  ('anglo-saxon-herzliya-pituach',    'https://www.madlan.co.il/agentsOffice/re_office_eAklpM13N0x'),
  ('iltam-real-estate',               'https://www.madlan.co.il/agentsOffice/re_office_bBVoiP4Aj55'),
  ('square34',                        'https://www.madlan.co.il/agentsOffice/re_office_j7Z75rWqKGU'),
  ('remax-one-kfar-saba',             'https://www.madlan.co.il/agentsOffice/re_office_dN3vv6p6jEq'),
  ('remax-atid-maale-adumim',         'https://www.madlan.co.il/agentsOffice/re_office_ioaDkw4iuhH'),
  ('anglo-saxon-mevaseret',           'https://www.madlan.co.il/agentsOffice/re_office_j8k8555PEgP'),
  ('racer-real-estate',               'https://www.madlan.co.il/agentsOffice/re_office_hfFpJ4UTlZg'),
  ('splus-real-estate',               'https://www.madlan.co.il/agentsOffice/re_office_LhVEMtqH6D'),
  ('anglo-saxon-petah-tikva',         'https://www.madlan.co.il/agentsOffice/re_office_ho6VMcBoXyg'),
  ('remax-infinity-petah-tikva',      'https://www.madlan.co.il/agentsOffice/re_office_iEZXMWFQ5ep'),
  ('alex-losky-real-estate-group',    'https://www.madlan.co.il/agentsOffice/re_office_knIVFSDHxXS'),
  ('anglo-saxon-hadera',              'https://www.madlan.co.il/agentsOffice/re_office_nWhtSREOou'),
  ('anglo-saxon-hod-hasharon',        'https://www.madlan.co.il/agentsOffice/re_office_dS9vzAPGlRT'),
  ('anglo-saxon-pardes-hanna',        'https://www.madlan.co.il/agentsOffice/re_office_eOLS3LQNwqK'),
  ('anglo-saxon-ramat-gan',           'https://www.madlan.co.il/agentsOffice/re_office_jnYyNr22JZ'),
  ('daon-group-real-estate',          'https://www.madlan.co.il/agentsOffice/re_office_bXjvkIGYS9a'),
  ('my-israel-property',              'https://www.madlan.co.il/agentsOffice/re_office_huEK9ZhoYne'),
  ('landsman',                        'https://www.madlan.co.il/agentsOffice/re_office_bjmOxLE8BKs'),
  ('remax-ocean',                     'https://www.madlan.co.il/agentsOffice/re_office_h7DTPNtBVFV')
) AS s(slug, url)
JOIN public.agencies a ON a.slug = s.slug
ON CONFLICT DO NOTHING;
