
WITH agency AS (SELECT 'a2c77541-753b-4e17-a368-e454e17ad8d4'::uuid AS id),
ag_agents AS (SELECT id FROM agents WHERE agency_id = (SELECT id FROM agency)),
jobs AS (SELECT id FROM import_jobs WHERE agency_id = (SELECT id FROM agency)),
props AS (SELECT id FROM properties WHERE agent_id IN (SELECT id FROM ag_agents) OR primary_agency_id = (SELECT id FROM agency)),
d1 AS (DELETE FROM favorites WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d2 AS (DELETE FROM featured_listings WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d3 AS (DELETE FROM featured_performance WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d4 AS (DELETE FROM guest_property_saves WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d5 AS (DELETE FROM image_hashes WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d6 AS (DELETE FROM import_conflicts WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d7 AS (DELETE FROM inquiries WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d8 AS (DELETE FROM listing_agency_reviews WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d9 AS (DELETE FROM listing_claim_requests WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d10 AS (DELETE FROM listing_quality_flags WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d11 AS (DELETE FROM listing_reports WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d12 AS (DELETE FROM location_module_events WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d13 AS (DELETE FROM market_insight_cache WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d14 AS (DELETE FROM outbound_clicks WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d15 AS (DELETE FROM price_context_events WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d16 AS (DELETE FROM price_drop_notifications WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d17 AS (DELETE FROM primary_agency_history WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d18 AS (DELETE FROM primary_disputes WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d19 AS (DELETE FROM property_co_agents WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d20 AS (DELETE FROM property_inquiries WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d21 AS (DELETE FROM property_source_observations WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d22 AS (DELETE FROM property_views WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d23 AS (DELETE FROM recently_viewed WHERE property_id IN (SELECT id FROM props) RETURNING 1),
d24 AS (DELETE FROM import_job_costs WHERE job_id IN (SELECT id FROM jobs) RETURNING 1),
d25 AS (DELETE FROM import_job_items WHERE job_id IN (SELECT id FROM jobs) RETURNING 1),
d26 AS (DELETE FROM properties WHERE id IN (SELECT id FROM props) RETURNING 1),
d27 AS (DELETE FROM import_jobs WHERE id IN (SELECT id FROM jobs) RETURNING 1)
SELECT 1;
